name: dn_signals
description: "Flutter plugin wrapper for Tencent DataNexus/GDT Action SDK conversion reporting."
version: 0.0.1
homepage: https://datanexus.qq.com/doc/develop/guider/sdk/ios/init

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.datanexus.dn_signals
        pluginClass: DnSignalsPlugin
      ios:
        pluginClass: DnSignalsPlugin
